%%
% This script calls the mnh_zmap_predict for harmonizing incoming cross-spectrum which requires the supplied norm file.


clear;

%%
% file of norm: used for harmonizing cross spectrum 
% please download from Synapse https://doi.org/10.7303/syn26712979, 
% it was calculated with data https://doi.org/10.7303/syn26712693, the training will released soon
path_norm='.\data\norm\norm_riemlogm_gfavfa_bava_study.mat';

% data table of incoming data: the data to be harmonized
% the table can be generated by step1
path_Dps='.\result\DPs_riemlogm_44_Barbados1978Malnutrition.csv';
% path of folder to save the result
path_out='.\result\';



% load neccesary variables for the prediction, which defined in training progress
%   tregs: saved regression model for training data table
%   level: levels definition of the hamonization model
%   resp: responses to be regressed
%   opt: options of the regression parameter
mnhs=load(path_norm,'tregs','level','resp','opt');
% set parameter in the structure for mnh_zmap_predict
% batch definition, which has to match the norm file load above
mnhs.batch={'study'}; 
mnhs.path_table=path_Dps;
mnhs.path_out=path_out;
% define which exsit batch to be used as the reference batch of incoming data
%  use as {'incomingBatchName', 'existBatchNameInNorm';'incomingBatchName', 'existBatchNameInNorm';...}
mnhs.reRefBatch={'Brb2_DEDAAS_Malnutrition','DEDAAS Barbados1978'};
% The tag to be append to the filename of output table to distinguish the project you are running with others. 
% Replace with your own task name
mnhs.tag=['zscore'];
% load data with the information above 
mnhs=mnh_create_predict(mnhs);



%% the table with harmonized data and its zscore will be saved in the caller
mnhs=MnhCaller(mnhs);


